version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: test.Dockerfile
    container_name: ecommerce_api
    ports:
      - '3500:3333'
    expose:
      - '3500'
    depends_on:
      - postgres


