FROM node:12-alpine

WORKDIR /app

ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV


ARG DATABASE_PORT
ENV DATABASE_PORT=$DATABASE_PORT
ARG DATABASE_HOST
ENV DATABASE_HOST=$DATABASE_HOST
ARG DATABASE_TYPE
ENV DATABASE_TYPE=$DATABASE_TYPE
ARG DATABASE_USERNAME
ENV DATABASE_USERNAME=$DATABASE_USERNAME
ARG DATABASE_PASSWORD
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ARG DATABASE
ENV DATABASE=$DATABASE
ARG SECRET
ENV SECRET=$SECRET
ARG EXPIRES_IN
ENV EXPIRES_IN=$EXPIRES_IN


# SERVER_PORT=3333
# DATABASE_PORT=5432
# DATABASE_HOST=localhost
# DATABASE_TYPE=postgres
# DATABASE_USERNAME=postgres
# DATABASE_PASSWORD=ecommerce
# DATABASE=postgres
# SECRET=80c2e210482616d14ee56bf9b7c9b48c
# EXPIRES_IN=5h

COPY package.json yarn.lock .env* ./
RUN yarn global add pm2 pg
RUN yarn install
ADD ./dist /app
EXPOSE 3000
CMD [ "pm2-runtime", "server.js"]


